---
development:
  cloud_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloud_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloud_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
production:
  cloud_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloud_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloud_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
test:
  cloud_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  cloud_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  cloud_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
